### ISSUE TITLE
CreateDatasource doesn't work when outside main module

### ISSUE THREAD

**Issue by elemoine** [mapnik/non-core-plugins#1]
Consider this simple Python script (`m.py`):

``` py
import mapnik
from mapnik import PythonDatasource
datasource = mapnik.Python(factory='PythonDatasource')
```

This works:

```
$ python m.py
```

This does not work:

```
$ python
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import m
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "t.py", line 3, in <module>
    datasource = mapnik.Python(factory='PythonDatasource')
  File "/usr/lib/python2.7/dist-packages/mapnik/__init__.py", line 617, in Python
    return CreateDatasource(keywords)
RuntimeError: AttributeError: 'module' object has no attribute 'PythonDatasource'

>>>
```

The problem is related to `CreateDatasource` considering the `__main__` module as the object having the factory.

I hit that problem when trying to create a `PythonDatasource` in my WSGI application. The workaround I have so far is:

``` py
sys.modules['__main__'].PythonDatasource = mapnik.PythonDatasource
```

which is a hack!

**Comment by gurneyalex** [comment]
the `__main__` module is hard coded in https://github.com/mapnik/non-core-plugins/blob/master/python/python_datasource.cpp#L61 

having a way to specify a module name would definitely be nicer. Failing that, mentioning the workaround mentioned in this issue in the documentation could be helpful, as the error message is quite obscure.

**Comment by gurneyalex** [comment]
@elemoine There is a way to give a module + class by using `"modulename:classname"`

This is actually mentioned in the documentation (cf. https://github.com/mapnik/non-core-plugins/commit/d5cf23dc77bad03635c182bc01e6888244eba10f#diff-7141304209be3da2a29ef8b0b79886fdR35) 

The main surprise is the use of ':' as a separator. My intuition made me try using a `.` which is the standard module separator in Python and it would be really nice if it worked.

**Comment by springmeyer** [comment]
Hi @elemoine and @gurneyalex - the python plugin is currently looking for a maintainer. So if you are finding it useful I would be happy to give you commit access here. I would also be happy to move it to its own repo if that would be easier. Just let me know. Also, overall in my opinion the python plugin is very useful for prototyping and for flexible rendering for small data. But because it is single threaded it is not very fast. If you need speed I would consider taking a look at vector tiles. This is more background for my comment at https://twitter.com/erilem/status/589125070355832833.

**Comment by elemoine** [comment]
Thanks for your response @springmeyer. My use-case involves creating a PNG image (or UTFGrid) from features read from a PostGIS database. The database query I use to read features is different from one HTTP request to the other, it depends on a number of parameters specified in the HTTP request's query string. My application already uses SQLAlchemy to read/write records from/to Postgres, so I've wanted to use SQLAlchemy for reading features as well, and I've been looking at the most performant solution for that. I experienced crashes with the PythonDatasource, so I'm using MemoryDatasource for the moment, but I still need to assess the performance that I can get out of that solution.

**Comment by springmeyer** [comment]
@elemoine - boost python needs patched for the python plugin to be usable: https://github.com/mapnik/mapnik/issues/1968#issuecomment-39277143. So that is likely the cause of the crashes. It is quite frustrating that the boost devs have not upstreamed that patch yet. I have been building boost with it for years.
